name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: test.svg
          user: sergeykonoplev5811
          base: ""
          plugin_achievements: yes




  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 5
          keep_minimum_runs: 5